version: '3'
services:
  mysql:
    hostname: spring-boot-example
    container_name: spring-boot-example
    image: mysql:5.7
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf # character set utf-8 설정
    env_file: # docker container에서 사용할 환경변수파일 (가장 우선)
      - ./mysql/.env
    ports:
      - 13306:3306 # 포트 포워딩 (host:container)